# Generated by Django 4.2 on 2023-04-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_remove_gallery_images_gallery_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='name',
            field=models.CharField(default='Галлерея', max_length=255, verbose_name='Название галлереи'),
        ),
    ]
